#! /bin/bash

[ -n "${IFACE}" ] || exit 0

for i in $(ethtool -g ${IFACE}|sed -ne 's,\([RT]X:\)[[:space:]]*\([0-9]\+\),\1\2,p'|head -n2);do
  IFS=: read key value <<<${i}
  if [[ "${key}" == "RX" ]];then
    max_rx=${value}
  elif [[ "${key}" == "TX" ]];then
    max_tx=${value}
  fi
done

ethtool -G ${IFACE} rx ${max_rx} tx ${max_tx}
