---

- name: Get brew prefix
  shell: >
    brew --prefix
  register: brew_prefix

- name: Add zsh to official shell
  lineinfile:
    path: "/etc/shells"
    line: "{{ brew_prefix.stdout }}/bin/zsh"

- name: Change users shell
  user:
    name: "{{ ansible_env.SUDO_USER }}"
    shell: "{{ brew_prefix.stdout }}/bin/zsh"
