---

- name: Install general packages
  homebrew:
    name: "{{ packages }}"
    update_homebrew: true
  vars:
    packages:
      - bash
      - coreutils
      - binutils
      - diffutils
      - gawk
      - gnutls
      - gzip
      - watch
      - wget
      - file-formula
      - git
      - openssh
      - postgresql
      - perl
      - rsync
      - unzip
      - zsh
      - sshuttle
      - nmap
      - ripgrep
      - bat
      - tmux
      - p7zip
      - htop
      - mosh
      - pwgen
      - reattach-to-user-namespace
#      - awless
      - kubectl
      - kube-ps1
      - kubectx
      - subnetcalc
      - iproute2mac
      - tree
      - pyenv
      - pyenv-virtualenv
      - fd
      - nvim
      - ed
      - findutils
      - gnu-indent
      - gnu-sed
      - gnu-tar
      - gnu-which
      - grep
      - awscli
      - warrensbox/tap/tfswitch
      - tokiwong/tap/helm-switcher

- name: Check if maccy is installed
  stat:
    path: "/Applications/Maccy.app"
  register: maccy

- name: Install apps with brew cask
  homebrew:
    name: "{{ packages }}"
    install_options: "cask"
  vars:
    packages:
      - maccy
  when: not maccy.stat.exists
