---

- name: Tap homebrew for awless
  homebrew_tap:
    name: "{{ packages }}"
  vars:
    packages:
      - wallix/awless

- name: Install GNU utils without overrides
  homebrew:
    name: "{{ packages }}"
    update_homebrew: true
  vars:
    packages:
      - bash
      - coreutils
      - binutils
      - diffutils
      - gawk
      - gnutls
      - gzip
      - watch
      - wget
      - file-formula
      - git
      - openssh
      - postgresql
      - perl
      - rsync
      - unzip
      - zsh
      - sshuttle
      - nmap
      - ripgrep
      - tmux
      - p7zip
      - htop
      - mosh
      - pwgen
      - reattach-to-user-namespace
      - awless
      - kubectl
      - kube-ps1
      - kubectx
      - subnetcalc
      - iproute2mac
      - tree
      - pyenv
      - pyenv-virtualenv
      - fd
      - nvim

- name: Install other GNU utils with default names
  homebrew:
    name: "{{ packages }}"
    install_options: with-default-names
  vars:
    packages:
      - ed
      - findutils
      - gnu-indent
      - gnu-sed
      - gnu-tar
      - gnu-which
      - grep

- name: Install apps with brew cask
  homebrew_cask:
    name: "{{ packages }}"
  vars:
    packages:
      - keepassxc
      - maccy
