---

- name: Tap brew packages
  homebrew_tap:
    name: "{{ packages }}"
  vars:
    packages:
      - homebrew/core
      - homebrew/cask-fonts
      # work
      - drone/drone

- name: Install general packages
  homebrew:
    name: "{{ packages }}"
    update_homebrew: true
  vars:
    packages:
      - bash
      - coreutils
      - binutils
      - diffutils
      - gawk
      - gnutls
      - gzip
      - watch
      - wget
      - file-formula
      - git
      - openssh
      - postgresql
      - perl
      - rsync
      - unzip
      - zsh
      - sshuttle
      - nmap
      - ripgrep
      - bat
      - tmux
      - p7zip
      - htop
      - mosh
      - pwgen
      - reattach-to-user-namespace
      - kubectl
      - kubectx
      - subnetcalc
      - iproute2mac
      - tree
      - pyenv
      - pyenv-virtualenv
      - fd
      - nvim
      - findutils
      - gnu-indent
      - gnu-sed
      - gnu-tar
      - gnu-which
      - grep
      - hugo
      - warrensbox/tap/tfswitch
      - tokiwong/tap/helm-switcher
      - helmfile
      - jq
      - fzf
      - parallel
      - go
      - docker
      - docker-buildx
      - docker-compose
      - colima
      # work
      - drone
      - saml2aws
      - jsonnet-bundler
      - go-jsonnet

- name: Install fonts
  homebrew:
    name: "{{ packages }}"
  vars:
    packages:
      - font-hack-nerd-font
  # Plugin exits with error however the fonts are installed
  ignore_errors: true

- name: Install apps with brew cask
  homebrew_cask:
    name: "{{ packages }}"
  # Plugin exits with error although the app is installed correctly
  ignore_errors: true
  vars:
    packages:
      - raycast
      - spotify
      - whatsapp
      - iterm2
      - telegram-desktop
      # - google-chrome
      - skype
      - logi-options-plus
      - vlc
  tags:
    - cask

- name: Get brew prefix
  shell: >
    brew --prefix
  register: _brew_prefix
  tags:
    - dotfiles
    - sync

- name: Set brew_prefix
  set_fact:
    brew_prefix: "{{ _brew_prefix.stdout }}"
  tags:
    - dotfiles
    - sync
