---

- name: Install oh-my-zsh
  shell: >
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    creates: "{{ ansible_user_dir }}/.oh-my-zsh"

- name: Check for existing powerline fonts
  stat:
    path: "{{ ansible_user_dir }}/Library/Fonts/Droid Sans Mono Dotted for Powerline.ttf"
  register: fonts

- name: Clone powerline fonts
  git:
    repo: https://github.com/powerline/fonts.git
    dest: "{{ ansible_user_dir }}/fonts"
    depth: 1
  when: not fonts.stat.exists

- name: Install powerline fonts
  shell: >
    ./install.sh
  args:
    chdir: "{{ ansible_user_dir }}/fonts"
  when: not fonts.stat.exists

- name: Cleanup powerline repo
  file:
    path: "{{ ansible_user_dir }}/fonts"
    state: absent

#- name: Install powerlevel9k theme
#  git:
#    repo: https://github.com/bhilburn/powerlevel9k.git
#    dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/themes/powerlevel9k"
#    update: false

- name: Install powerlevel10k theme
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/themes/powerlevel10k"
    update: false
    depth: 1

- name: Install fzf-z
  git:
    repo: https://github.com/andrewferrier/fzf-z.git
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/plugins/fzf-z"
    depth: 1

- name: Install zsh-dircolors-solarized
  git:
    repo: https://github.com/joel-porquet/zsh-dircolors-solarized
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/plugins/zsh-dircolors-solarized"
    depth: 1

- name: Create cache file for fzf-z
  file:
    path: "{{ ansible_user_dir }}/.z"
    state: touch
    owner: "{{ ansible_user_id }}"
    group: "staff"
