---
- name: Install python libs only for localhost
  pip:
    name: "{{ packages }}"
    virtualenv: "/Users/{{ ansible_env.SUDO_USER }}/.venv/main"
    virtualenv_command: "python3"
  vars:
    packages:
      - docker-compose
      - ipython

- name: Install oh-my-zsh
  shell: >
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  args:
    creates: "/Users/{{ ansible_env.SUDO_USER }}/.oh-my-zsh"

- name: Check for existing powerline fonts
  stat:
    path: "/Users/{{ ansible_env.SUDO_USER }}/Library/Fonts/Droid Sans Mono Dotted for Powerline.ttf"
  register: fonts

- name: Clone powerline fonts
  git:
    repo: https://github.com/powerline/fonts.git
    dest: "/Users/{{ ansible_env.SUDO_USER }}/fonts"
    depth: 1
  when: not fonts.stat.exists

- name: Install powerline fonts
  shell: >
    install.sh
  args:
    chdir: "/Users/{{ ansible_env.SUDO_USER }}/fonts"
  when: not fonts.stat.exists

- name: Cleanup powerline repo
  file:
    path: "/Users/{{ ansible_env.SUDO_USER }}/fonts"
    state: absent

- name: Install powerlevel9k theme
  git:
    repo: https://github.com/bhilburn/powerlevel9k.git
    dest: "/Users/{{ ansible_env.SUDO_USER }}/.oh-my-zsh/custom/themes/powerlevel9k"

- name: Install zsh-dircolors-solarized
  git:
    repo: https://github.com/liangguohuan/zsh-dircolors-solarized
    dest: "/Users/{{ ansible_env.SUDO_USER }}/.oh-my-zsh/custom/plugins/zsh-dircolors-solarized"

- name: Install fzf
  git:
    repo: https://github.com/junegunn/fzf.git
    dest: "/Users/{{ ansible_env.SUDO_USER }}/.fzf"
    depth: 1

- name: Install grml .vimrc
  get_url:
    url: "https://grml.org/console/{{ item }}"
    dest: "/Users/{{ ansible_env.SUDO_USER }}/.{{ item }}"
  with_items:
    - vimrc

- name: Create dirs for pathogen
  file:
    path: "/Users/{{ ansible_env.SUDO_USER }}/.vim/{{ item }}"
    state: directory
  with_items:
    - autoload
    - bundle

- name: Setup vim pathogen
  get_url:
    url: "https://tpo.pe/pathogen.vim"
    dest: "/Users/{{ ansible_env.SUDO_USER }}/.vim/autoload/pathogen.vim"

- name: Setup Vundle
  git:
    repo: "https://github.com/VundleVim/Vundle.vim.git"
    dest: "/Users/{{ ansible_env.SUDO_USER }}/.vim/bundle/Vundle.vim"

- name: Init vim plugins
  shell: >
    vim +PlugInstall +PluginInstall +qall
  args:
    creates: "/Users/{{ ansible_env.SUDO_USER }}/.vim/plugged/nerdtree/"
  when:
    - vim_plugins_install is defined
    - vim_plugins_install | bool
