---

- name: Install oh-my-zsh
  shell: >
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    creates: "{{ ansible_user_dir }}/.oh-my-zsh"

- name: Install powerlevel10k theme
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/themes/powerlevel10k"
    update: false
    depth: 1

- name: Install fzf-z
  git:
    repo: https://github.com/andrewferrier/fzf-z.git
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/plugins/fzf-z"
    depth: 1

- name: Install zsh-dircolors-solarized
  git:
    repo: https://github.com/joel-porquet/zsh-dircolors-solarized
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/plugins/zsh-dircolors-solarized"
    depth: 1

- name: Create cache file for fzf-z
  file:
    path: "{{ ansible_user_dir }}/.z"
    state: touch
    owner: "{{ ansible_user_id }}"
    group: "staff"

- name: Install Neovim Packer
  git:
    repo: https://github.com/wbthomason/packer.nvim
    dest: "{{ ansible_user_dir }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
    depth: 1
