---

- name: Create pyenv main virtualenv
  shell: >
    pyenv virtualenv {{ virtualenv_version }} main
  args:
    creates: "{{ ansible_user_dir }}/.pyenv/versions/{{ virtualenv_version }}/envs/main/"

- name: Install python libs only for localhost
  pip:
    requirements: "{{ playbook_dir }}/../../requirements.txt"
    virtualenv: "{{ ansible_user_dir }}/.pyenv/versions/{{ virtualenv_version }}/envs/main/"

- name: Install oh-my-zsh
  shell: >
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  args:
    creates: "{{ ansible_user_dir }}/.oh-my-zsh"

- name: Check for existing powerline fonts
  stat:
    path: "{{ ansible_user_dir }}/Library/Fonts/Droid Sans Mono Dotted for Powerline.ttf"
  register: fonts

- name: Clone powerline fonts
  git:
    repo: https://github.com/powerline/fonts.git
    dest: "{{ ansible_user_dir }}/fonts"
    depth: 1
  when: not fonts.stat.exists

- name: Install powerline fonts
  shell: >
    install.sh
  args:
    chdir: "{{ ansible_user_dir }}/fonts"
  when: not fonts.stat.exists

- name: Cleanup powerline repo
  file:
    path: "{{ ansible_user_dir }}/fonts"
    state: absent

- name: Install powerlevel9k theme
  git:
    repo: https://github.com/bhilburn/powerlevel9k.git
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/themes/powerlevel9k"
    update: false

- name: Install fzf-z
  git:
    repo: https://github.com/andrewferrier/fzf-z.git
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/plugins/fzf-z"
    depth: 1
