---

- name: Create GOPATH directory
  file:
    path: "{{ ansible_user_dir }}/go"
    state: directory

- name: Install hugo
  shell: >
    go install -tags extended github.com/gohugoio/hugo@latest
  tags:
    - hugo

- name: Install Go packages
  shell: >
    go install "{{ item }}"
  loop: "{{ go_packages }}"
  register: _go_packages_installation
  async: 60
  poll: 0

- name: Wait for go packages installation task to finish
  async_status:
    jid: "{{ item.ansible_job_id }}"
  register: _jobs_go_packages_installation
  retries: 600
  delay: 2
  until: _jobs_go_packages_installation.finished
  loop: "{{ _go_packages_installation.results }}"
