---

- import_tasks: brew.yml
  tags: brew
- import_tasks: os.yml
- import_tasks: dotfiles.yml
  tags: dotfiles
- import_tasks: go.yml
  tags: go

- name: Synchronize configs
  synchronize:
    src: Users/
    dest: "{{ ansible_user_dir }}/"
    archive: true
  tags:
    - dotfiles
    - sync
