---
- name: Create screenshots dir
  file:
    path: "{{ ansible_user_dir }}/Screenshots"
    state: directory

- name: Set default screenshots location
  shell: >
    defaults write com.apple.screencapture location ~/Screenshots

- name: Enshure mpd.db file exists
  file:
    path: "{{ ansible_user_dir }}/.mpd/mpd.db"
    state: touch

- name: Enshure playlists directory exists
  file:
    path: "{{ ansible_user_dir }}/.mpd/playlists"
    state: directory

- name: Create symlink to /Volumes/music
  file:
    src: "/Volumes/music"
    dest: "{{ ansible_user_dir }}/Music/mounted"
    state: link
    force: yes

- name: Configure ssh client
  lineinfile:
    dest: "{{ ansible_user_dir }}/.ssh/config"
    line: "{{ item }}"
    owner: "{{ ansible_user_id }}"
    group: "staff"
    create: yes
  with_items:
    - Host *
    - ForwardAgent yes
    - StrictHostKeyChecking no
    - ControlMaster auto
    - ControlPath /tmp/%r@%h:%p
    - ControlPersist 10m
    - Include ~/.ssh/config.d/*
