---

- name: Create screenshots dir
  file:
    path: "{{ ansible_user_dir }}/Screenshots"
    state: directory

- name: Set default screenshots location
  shell: >
    defaults write com.apple.screencapture location ~/Screenshots

- name: Check if ~/.ssh/config exists
  stat:
    path: "{{ ansible_user_dir }}/.ssh/config"
  register: ssh_config

- name: Configure ssh client
  lineinfile:
    dest: "{{ ansible_user_dir }}/.ssh/config"
    line: "{{ item }}"
    owner: "{{ ansible_user_id }}"
    group: "staff"
    create: yes
  with_items:
    - Host *
    - ForwardAgent yes
    - StrictHostKeyChecking no
    - ControlMaster auto
    - ControlPath /tmp/%r@%h:%p
    - ControlPersist 10m
    - Include ~/.ssh/config.d/*
  when: not ssh_config.stat.exists
