---
- name: Tap homebrew for awless
  homebrew_tap:
    name: wallix/awless

- name: Install GNU utils without overrides
  homebrew:
    name: "{{ packages }}"
  vars:
    packages:
    - bash
    - coreutils
    - binutils
    - diffutils
    - gawk
    - gnutls
    - gzip
    - watch
    - wget
    - file-formula
    - git
    - openssh
    - perl
    - rsync
    - unzip
    - zsh
    - sshuttle
    - nmap
    - mpd
    - mpc
    - ncmpcpp
    - ripgrep
    - tmux
    - p7zip
    - htop
    - mosh
    - pwgen
    - reattach-to-user-namespace
    - awless
    - kubectl

- name: Install other GNU utils with default names
  homebrew:
    name: "{{ packages }}"
    install_options: with-default-names
  vars:
    packages:
      - ed
      - findutils
      - gnu-indent
      - gnu-sed
      - gnu-tar
      - gnu-which
      - grep

- name: Install wdiff & vim
  homebrew:
    name: "{{ item.name }}"
    install_options: "{{ item.opts }}"
  with_items:
    - { name: 'wdiff', opts: 'with-gettext' }
    - { name: 'vim', opts: 'override-system-vi' }
