- homebrew:
    name: md5sha1sum
    state: present
  become: no

- name: install python libs
  pip:
    name: "{{ item }}"
  with_items:
    - virtualenv
    - docker-compose

- name: install grml zsh
  get_url:
    url: https://git.grml.org/f/grml-etc-core/etc/zsh/zshrc
    dest: "/Users/{{ ansible_env.SUDO_USER }}/.zshrc"
    owner: "{{ ansible_env.SUDO_USER }}"
    force: yes
- name: configuring grml
  lineinfile:
    dest: "/Users/{{ ansible_env.SUDO_USER }}/.zshrc"
    line: "{{ item.to }}"
    regexp: "{{ item.from }}"
    backrefs: yes
  with_items:
    - from: '(\s+)format \"\$\{MAGENTA\}.*'
      to: '\1format "${MAGENTA}(${NO_COLOR}%s${MAGENTA})${YELLOW}-${MAGENTA}[${GREEN}%b${MAGENTA}${MAGENTA}]${RED}%c${GREEN}%u${NO_COLOR} "'
    - from: "^(bind2maps.*insert-datestamp)"
      to: '#\1'


- name: synchronize configs
  synchronize:
    src: Users/
    dest: "/Users/{{ ansible_env.SUDO_USER }}/"
    archive: yes

- name: templating .gitconfig
  template:
    src: Users/.gitconfig
    dest: "/Users/{{ ansible_env.SUDO_USER }}/.gitconfig"

- name: init vim plugins
  shell: >
    vim +PlugInstall +qall

- name: set right file owner
  file:
    path: "/Users/{{ ansible_env.SUDO_USER }}"
    state: directory
    recurse: yes
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "staff"

# vi:syntax=yaml
