---
- import_tasks: brew.yml

- name: configure screenshots dir
  file:
    path: "/Users/{{ ansible_env.SUDO_USER }}/Screenshots"
    state: directory
- shell: >
    defaults write com.apple.screencapture location ~/Screenshots
  become: no

- name: unlink gnu-ls without color
  file:
    path: '/usr/local/opt/coreutils/libexec/gnubin/ls'
    state: absent

- name: install python libs
  pip:
    name: "{{ item }}"
  with_items:
    - virtualenv
    - docker-compose


- name: install grml basic configs
  get_url:
    url: "https://grml.org/console/{{ item }}"
    dest: "/Users/{{ ansible_env.SUDO_USER }}/.{{ item }}"
    owner: "{{ ansible_env.SUDO_USER }}"
  with_items:
    - zshrc
    - vimrc

- name: add zsh to official shell
  lineinfile:
    path: "/etc/shells"
    line: "/usr/local/bin/zsh"

- name: change users shell
  user:
    name: "{{ ansible_env.SUDO_USER }}"
    shell: "/usr/local/bin/zsh"


- name: synchronize configs
  synchronize:
    src: Users/
    dest: "/Users/{{ ansible_env.SUDO_USER }}/"
    archive: yes

- name: creating mpd config dirs
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "staff"
  with_items:
    - "/Users/{{ ansible_env.SUDO_USER }}/.config/mpd"
    - "/usr/local/etc/mpd"
- name: templating mpd
  template:
    src: Users/.config/mpd/mpd.conf
    dest: "/Users/{{ ansible_env.SUDO_USER }}/.config/mpd/mpd.conf"
- name: creating symlink to mpd config
  file:
    dest: /usr/local/etc/mpd/mpd.conf
    src: "/Users/{{ ansible_env.SUDO_USER }}/.config/mpd/mpd.conf"
    state: link
    force: yes

- name: init vim plugins
  shell: >
    vim +PlugInstall +qall

- name: configure ssh client
  lineinfile:
    dest: "/Users/{{ ansible_env.SUDO_USER }}/.ssh/config"
    line: "{{ item }}"
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "staff"
    create: yes
  with_items:
    - Host *
    - ForwardAgent yes
    - StrictHostKeyChecking no
    - ControlMaster auto
    - ControlPath /tmp/%r@%h:%p
    - ControlPersist 10m
    - Include ~/.ssh/config.d/*

- name: set right file owner
  file:
    path: "/Users/{{ ansible_env.SUDO_USER }}"
    state: directory
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "staff"
