---
- import_tasks: brew.yml
  become: no

- name: configure screenshots dir
  file:
    path: "/Users/{{ ansible_env.SUDO_USER }}/Screenshots"
    state: directory
- shell: >
    defaults write com.apple.screencapture location ~/Screenshots
  become: no

- name: unlink gnu-ls without color
  file:
    path: '/usr/local/opt/coreutils/libexec/gnubin/ls'
    state: absent

- name: install python libs
  pip:
    name: "{{ item }}"
  with_items:
    - virtualenv
    - docker-compose
    - ipython


- name: install grml basic configs
  get_url:
    url: "https://grml.org/console/{{ item }}"
    dest: "/Users/{{ ansible_env.SUDO_USER }}/.{{ item }}"
  become: no
  with_items:
    - zshrc
    - vimrc

- name: add zsh to official shell
  lineinfile:
    path: "/etc/shells"
    line: "/usr/local/bin/zsh"

- name: change users shell
  user:
    name: "{{ ansible_env.SUDO_USER }}"
    shell: "/usr/local/bin/zsh"


- name: synchronize configs
  synchronize:
    src: Users/
    dest: "/Users/{{ ansible_env.SUDO_USER }}/"
    archive: yes
  become: no


- name: create dirs for pathogen
  file:
    path: "/Users/{{ ansible_env.SUDO_USER }}/.vim/{{ item }}"
    state: directory
  become: no
  with_items:
    - autoload
    - bundle

- name: setup vim pathogen
  get_url:
    url: "https://tpo.pe/pathogen.vim"
    dest: "/Users/{{ ansible_env.SUDO_USER }}/.vim/autoload/pathogen.vim"
  become: no

- name: setup Vundle
  git:
    repo: "https://github.com/VundleVim/Vundle.vim.git"
    dest: "/Users/{{ ansible_env.SUDO_USER }}/.vim/bundle/Vundle.vim"
  become: no

- name: init vim plugins
  shell: "vim +PlugInstall +qall"
  become: no


- name: setup mpd
  file:
    path: "/Users/{{ ansible_env.SUDO_USER }}/.mpd/{{ item }}"
    state: touch
  with_items:
    - "playlists"
    - "mpd.db"


- name: configure ssh client
  lineinfile:
    dest: "/Users/{{ ansible_env.SUDO_USER }}/.ssh/config"
    line: "{{ item }}"
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "staff"
    create: yes
  with_items:
    - Host *
    - ForwardAgent yes
    - StrictHostKeyChecking no
    - ControlMaster auto
    - ControlPath /tmp/%r@%h:%p
    - ControlPersist 10m
    - Include ~/.ssh/config.d/*
  become: no

- name: set right file owner
  file:
    path: "/Users/{{ ansible_env.SUDO_USER }}"
    state: directory
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "staff"
