- name: installing packages
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - vim
    - zsh
    - openbox
    - tint2
    - keepassx
  become: yes

- name: synchronize configs
  synchronize:
    src: home/
    dest: "/home/{{ ansible_env.SUDO_USER }}/"
    archive: yes

- name: init vim plugins
  shell: >
    vim +PlugInstall +qall
