---
- import_tasks: Darwin.yml
  when: ansible_os_family == "Darwin"

- name: Install necessary admin packages
  become: yes
  package:
    name: "{{ packages }}"
  vars:
    packages:
      - vim
      - tmux
      - mosh
  when: ansible_os_family != "Darwin"

- name: Copy .local configs
  copy:
    src: home/
    dest: "{{ ansible_user_dir }}/"
  tags: copy_configs
