---
- name: Compress directory whith key files
  archive:
    path: "{{openvpn_keydir}}/*"
    dest: "{{openvpn_etcdir}}/keys.tgz"

- name: Copy archive to localhost
  fetch:
    src: "{{openvpn_etcdir}}/keys.tgz"
    dest: "{{role_path}}/files/"
    flat: yes

- name: Encrypt key files
  command:
    ansible-vault encrypt "{{role_path}}/files/keys.tgz"
  args:
    chdir: '{{playbook_dir}}/../..'
  become: no
  delegate_to: localhost
