---
- name: Create iptables-rules
  iptables:
    action: insert
    table: nat
    chain: POSTROUTING
    out_interface: '{{ ansible_default_ipv4.interface }}'
    jump: MASQUERADE

- name: Install Iptables
  apt: name=iptables-persistent

- name: Save iptables
  shell: iptables-save > /etc/iptables/rules.v4
