vim.keymap.set('n', '<leader>ga', ':G add %:p<CR><CR>')

vim.keymap.set('n', '<leader>gs', ':G<CR>')
vim.keymap.set('n', '<leader>gc', ':G commit -v -q<CR>')
vim.keymap.set('n', '<leader>gca', ':G commit -v -q --all<CR>')
vim.keymap.set('n', '<leader>gt',':G commit -v -q %:p<CR>')
vim.keymap.set('n', '<leader>gd',':Gvdiff<CR>')
vim.keymap.set('n', '<leader>ge',':Gedit<CR>')
vim.keymap.set('n', '<leader>gr',':Gread<CR>')
vim.keymap.set('n', '<leader>gw',':Gwrite<CR><CR>')
vim.keymap.set('n', '<leader>gl',':bot Gclog<CR>:bot copen<CR>')
vim.keymap.set('n', '<leader>gp',':G push origin @<CR>')
vim.keymap.set('n', '<leader>gP',':G push -f origin @<CR>')
vim.keymap.set('n', '<leader>gm',':G diff origin/master<CR>')
vim.keymap.set('n', '<leader>go',':! git pull --verbose --no-rebase --autostash origin $(basename $(git symbolic-ref refs/remotes/origin/HEAD))<CR>')
vim.keymap.set('n', '<leader>gcb',':G checkout --track -b<Space>')
vim.keymap.set('n', '<leader>gco',':G checkout<Space>')
vim.keymap.set('n', '<leader>gfa',':! git fetch --all --prune --jobs=10<CR>')
vim.keymap.set('n', '<leader>gup', ':! git fetch --all --prune --jobs=10 && git pull --no-rebase --verbose --autostash origin $(git branch --show-current)<CR>')
