---
- name: Configure screenshots dir
  file:
    path: "/Users/{{ ansible_env.SUDO_USER }}/Screenshots"
    state: directory
- shell: >
    defaults write com.apple.screencapture location ~/Screenshots
  become: no

- name: Unlink gnu-ls without color
  file:
    path: '/usr/local/opt/coreutils/libexec/gnubin/ls'
    state: absent


- name: Add zsh to official shell
  lineinfile:
    path: "/etc/shells"
    line: "/usr/local/bin/zsh"

- name: Change users shell
  user:
    name: "{{ ansible_env.SUDO_USER }}"
    shell: "/usr/local/bin/zsh"


- name: Synchronize configs
  synchronize:
    src: Users/
    dest: "/Users/{{ ansible_env.SUDO_USER }}/"
    archive: yes
  become: no
  tags: copy_configs



- name: Enshure mpd.db file exists
  file:
    path: "/Users/{{ ansible_env.SUDO_USER }}/.mpd/mpd.db"
    state: touch

- name: Enshure playlists directory exists
  file:
    path: "/Users/{{ ansible_env.SUDO_USER }}/.mpd/playlists"
    state: directory

- name: Create symlink to /Volumes/music
  file:
    src: "/Volumes/music"
    dest: "/Users/{{ ansible_env.SUDO_USER }}/Music/mounted"
    state: link


- name: Configure ssh client
  lineinfile:
    dest: "/Users/{{ ansible_env.SUDO_USER }}/.ssh/config"
    line: "{{ item }}"
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "staff"
    create: yes
  with_items:
    - Host *
    - ForwardAgent yes
    - StrictHostKeyChecking no
    - ControlMaster auto
    - ControlPath /tmp/%r@%h:%p
    - ControlPersist 10m
    - Include ~/.ssh/config.d/*
  become: no

- name: Set right file owner
  file:
    path: "/Users/{{ ansible_env.SUDO_USER }}"
    state: directory
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "staff"
